"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import sys
from pathlib import Path
import os


# Specify log directory
LOG_PATH = '/data/logs'


PROMETHEUS_METRIC_NAMESPACE = "container_1"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True   # Output logs to console during debugging, disable in production

ALLOWED_HOSTS = ['*']

APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_prometheus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

PLATFORM = "Windows" if sys.platform == "win32" else "Linux"

# # Create log directory path
# if 'SERVICE_LOG_PATH' in os.environ:
#     LOG_PATH = os.environ.get('SERVICE_LOG_PATH')
#     print("Find the log path({}) from environment variable.".format(LOG_PATH))
# else:
#     LOG_PATH = os.path.join(BASE_DIR, 'log')
#     print("Cannot get the log path from environment variable! The default log path({}) will be used.".format(LOG_PATH))


# Create log directory if it doesn't exist
if not os.path.isdir(LOG_PATH):
    os.makedirs(LOG_PATH)

saved_days = 30

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
                      '[%(levelname)s][%(message)s]'
        },
    },
    # Filters
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # Save to file with automatic rotation
            'filename': os.path.join(LOG_PATH, "info.log"),  # Log file
            'maxBytes': 1024 * 1024 * 10,  # Log size 10MB
            'backupCount': saved_days,  # Keep 10 days of logs
            'formatter': 'standard',
            'encoding': 'utf-8',    # Set encoding to prevent Chinese character encoding issues
        },
        'warning': {
            'level': 'WARNING',
            'class': 'logging.handlers.TimedRotatingFileHandler',  # Save to file with daily rotation
            'filename': os.path.join(LOG_PATH, "warn.log"),  # Log file
            'when': 'MIDNIGHT',  # Rotate at midnight
            'backupCount': saved_days,  # Keep 30 days of logs
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'request_log': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',  # Save to file with automatic rotation
            'filename': os.path.join(LOG_PATH, "request.log"),  # Log file
            'maxBytes': 1024 * 1024 * 10,  # Log size 10MB
            'backupCount': saved_days,  # Keep 10 days of logs
            'formatter': 'standard',
            'encoding': 'utf-8',    # Set encoding to prevent Chinese character encoding issues
        }
    },
    'loggers': {
        # Default logger configuration
        '': {
            'handlers': ['console', 'default', 'warning'],  # Remove 'console' in production
            'level': 'DEBUG',
            'propagate': True,      # Propagate: Whether to pass log messages to parent logger instances
        },
        'django.request': {
            'handlers': ['request_log'],
            'propagate': True,
        },
    }
}